### ISSUE TITLE
Default Password

### ISSUE THREAD

**Issue by loren138** [psd401/cas4-overlay#1]
Hey so, since I think this is your actual deployed version of CAS, you should remove this line: https://github.com/psd401/cas4-overlay/blob/master/src/main/webapp/WEB-INF/deployerConfigContext.xml#L65

It enables the default login of casuser and Mellon to get into your website, and you probably don't want that enabled...

**Comment by AshMartian** [comment]
@loren138 Thank you for pointing this out to us!
